version: '3.7'
services:
  service-1:
    container_name: "service-1"
    image: dwordie/service-1
    build: service-1
    ENVIRONMENT:
      DATABASE_URI:
    ports:
    - target: 5000
      published: 5000
      protocol: tcp

  service-2:
    container_name: "service-2"
    image: dwordie/service-2
    build: service_2/

  service-3:
    container_name: "service-3"
    image: dwordie/service-3
    build: service_3/

  service-4:
    container_name: "service-4"
    image: dwordie/service-4
    build: service_4/